### ISSUE TITLE
Compilation failure on GCC 9.3.0 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by phobozad** [unaPoloGTIc/common-raii#1]
As part of the [trex-pam](https://github.com/unaPoloGTIc/trex-pam) project, this module fails to compile on GCC 9.3.0 as shipped with Ubuntu 20.04.

Errors seen:
```
trex-pam.cpp: In constructor ‘userRecord::userRecord(std::string)’:
trex-pam.cpp:61:18: error: variable ‘std::stringstream s’ has initializer but incomplete type
   61 |     stringstream s{ss};
      |                  ^
trex-pam.cpp: In member function ‘std::string webServerRaii::start()’:
trex-pam.cpp:298:20: error: variable ‘std::stringstream ss’ has initializer but incomplete type
  298 |       stringstream ss{};
      |                    ^~
```

Not sure if this is specific to GCC 9.3.0 though I suspect not.

Appears that there is just a missing include for `#include <sstream>`
